apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-api-app
  template:
    metadata:
      labels:
        app: flask-api-app
    spec:
      containers:
      - name: flask-api-app
        image: elizabeth001/flask-api-app:latest
        ports:
        - containerPort: 5000